- hosts: server
  become: true
  tasks:
    - name: update apt and upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service: 
        name: nginx
        state: started